### ISSUE TITLE
Carousel with only 2 slides won't transition correctly with "slide"

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/responsive-carousel#150]
To reproduce, make a carousel with only two slides and the slide (not fade) transition.

* The problem is that the carousel is in a constant state of adding a class to the active, next, and previous slides.
* When there are two slides, the next slide gets the previous class as well so it breaks with the animation because next and prev classes are both applied simultaneously.

* It’s not just that it shouldn’t get the previous class, but that it should probably get the class it really needs just before the transition, so we know which one to use

**Comment by johnbender** [comment]
@scottjehl 

I can't seem to reproduce in the functional tests:

https://150-origin-responsive-carousel.fgview.com/test/functional/slide.html

**Comment by johnbender** [comment]
@scottjehl 

So here's what I found.

https://150-origin-responsive-carousel.fgview.com/test/functional/slide.html

If you reduce the transition speed it's impossible to reproduce. This is because, starting from the first slide, after clicking next, and after the transition of both slides to the left, the first slide then makes _another_ transition behind the scenes to the stack on the right side of the viewport. 

If it moves instantly the problem goes away completely, otherwise when the user clicks previous the first slide can be mid transition to the right (the stack) and starts a new, garbled transition in from the left. 

It seems like we need to disable transitions for all slides until they are in position and then apply the actual visible transition to both `$to` and `$from`, but I haven't been able to get that to work reliably yet.
