### ISSUE TITLE
Carousel Slide sprints from the start to finish on loop.

### ISSUE THREAD

**Issue by aphillipo** [filamentgroup/responsive-carousel#86]
The next carousel element jumps from the start to the end on loop.  You can see it briefly move from one end rapidly to the other.

I assume this is not intentional to see this transition.  It's presumably a CSS3 transitions thing?

Maybe remove and readd the transition on the move of the carousel pane.

**Comment by cshold** [comment]
I've run into the same issue today. Since it's a CSS3 transition, I don't think there is a way to set the `left` property without an animation, and then readd the transition. Some hacky JS may be in order...

Most other carousels that include a loop will clone the appropriate element so this isn't an issue.
